<div class="block-container">
    <div class="block-title">
        <div class="span">information</div>
    </div>
    <div class="block-content">
        <ul>
            <li><a href="#"><span>About us</span></a></li>
            <li><a href="#"><span>Customer Service</span></a></li>
            <li><a href="#"><span>Privacy Policy</span></a></li>
            <li><a href="#"><span>Site Map</span></a></li>
            <li><a href="#"><span>Search Themes</span></a></li>
            <li><a href="#"><span>Advanced and Returns</span></a></li>
            <li><a href="#"><span>Contact Us</span></a></li>
        </ul>
    </div>
</div>