<div class="block-container">
    <div class="block-title">
        <span>my accout</span>
    </div>
    <div class="block-content">
        <ul>
            <li><a href="#"><span>Sign in</span></a></li>
            <li><a href="#"><span>View Cart</span></a></li>
            <li><a href="#"><span>My Wishlist</span></a></li>
            <li><a href="#"><span>Track My Order</span></a></li>
            <li><a href="#"><span>Help</span></a></li>
        </ul>
    </div>
</div>