<div class="block-container">
    <div class="block-title">
        <span>why buy from us</span>
    </div>
    <div class="block-content">
        <ul>
            <li><a href="#"><span>Shipping & Returns</span></a></li>
            <li><a href="#"><span>Secure Shopping</span></a></li>
            <li><a href="#"><span>International Shipping</span></a></li>
            <li><a href="#"><span>Affiliatis</span></a></li>
            <li><a href="#"><span>Group Sales</span></a></li>
        </ul>
    </div>
</div>