<div class="banners-wrapper">
   <div class="top-banners-wrapper">
    <div class="container-left">
            <img src="<?php echo $this->getSkinUrl('images/banners/banner1.jpg'); ?>" alt="Demo">
            <span class="title">new<br>collection</span>
    </div>
    <div class="container-right">
            <img src="<?php echo $this->getSkinUrl('images/banners/banner2.jpg'); ?>" alt="Demo">
            <div class="action-banner">
            <img src="<?php echo $this->getSkinUrl('images/banners/banner3.jpg'); ?>" alt="Demo">
            </div>
            <span class="title-wrapper">
        <span class="title">Shoes</span><br><span class="title-action">30%<br></span><span class="title-action-bold">OFF</span>
        </span>
        
    </div>
</div>
    <div class="bottom-banners-wrapper">
       
            <span class="title">Free Shipping<br>14 Days Return Policy<br>Largest Selection wares</span>
     
        <div class="banner">
            <img src="<?php echo $this->getSkinUrl('images/banners/banner4.jpg'); ?>" alt="Demo">
        </div>
        

    </div>
 </div>