<div class="banners-wrapper">
    <div class="container-left">
        <div class="banner">
            <img src="<?php echo $this->getSkinUrl('images/banners/banner1.jpg'); ?>" alt="Demo">
            <span class="title">new collection</span>
        </div>
    </div>
    <div class="container-right">
        <div class="banner">
            <img src="<?php echo $this->getSkinUrl('images/banners/banner2.jpg'); ?>" alt="Demo">
        </div>
        <div class="banner">
            <img src="<?php echo $this->getSkinUrl('images/banners/banner3.jpg'); ?>" alt="Demo">
            <span class="title">shoes 30% off</span>
        </div>
    </div>
    <div class="container-wide">
        <div class="banner">
            <img src="<?php echo $this->getSkinUrl('images/banners/banner4.jpg'); ?>" alt="Demo">
        </div>
        <div class="banner">
            <span class="title">Free Shipping 14 Days Return Policy Largest Selection wares</span>
        </div>


    </div>
</div>
